# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Govard < Formula
  desc "Govard local development orchestrator CLI"
  homepage "https://github.com/ddtcorex/govard"
  version "1.75.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ddtcorex/govard/releases/download/v1.75.0/govard_1.75.0_Darwin_amd64.tar.gz"
      sha256 "9e62adbda7e1602eb51b1516478cad01c0b0359b1776552d07f8dcdd24b47199"

      define_method(:install) do
        bin.install "govard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ddtcorex/govard/releases/download/v1.75.0/govard_1.75.0_Darwin_arm64.tar.gz"
      sha256 "b67f401d8d6938b1aa9ed3f214c1fa817aaa45b22055ee672b15992d284eddb7"

      define_method(:install) do
        bin.install "govard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddtcorex/govard/releases/download/v1.75.0/govard_1.75.0_Linux_amd64.tar.gz"
      sha256 "13ba50c6885b44e49289aeddd93fd48f4e6a4ec071bb1db562d5552e6bd3878b"
      define_method(:install) do
        bin.install "govard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddtcorex/govard/releases/download/v1.75.0/govard_1.75.0_Linux_arm64.tar.gz"
      sha256 "b24cc5146b3732b51101dffe5e2dec587c66e91a5a5c3c0c78742aa19d8468e5"
      define_method(:install) do
        bin.install "govard"
      end
    end
  end

  def post_install
    (bin/".install-source").write "brew"
  end

  test do
    system "#{bin}/govard", "version"
  end
end
