# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Govard < Formula
  desc "Govard local development orchestrator CLI"
  homepage "https://github.com/ddtcorex/govard"
  version "1.71.0-beta.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ddtcorex/govard/releases/download/v1.71.0-beta.6/govard_1.71.0-beta.6_Darwin_amd64.tar.gz"
      sha256 "2cc0c0d6c929bbe7a1adf469add7e73765b45f857678db3363fd161246618111"

      define_method(:install) do
        bin.install "govard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ddtcorex/govard/releases/download/v1.71.0-beta.6/govard_1.71.0-beta.6_Darwin_arm64.tar.gz"
      sha256 "447ecb857ba608a15696f4cd6d72ef20adc96d718f11ab0abf4b2a0d737a8e16"

      define_method(:install) do
        bin.install "govard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddtcorex/govard/releases/download/v1.71.0-beta.6/govard_1.71.0-beta.6_Linux_amd64.tar.gz"
      sha256 "e1e6ab8159d1fd3ad592f1100989ba3875fc8707ae06de30b12ee2361cb636d9"
      define_method(:install) do
        bin.install "govard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddtcorex/govard/releases/download/v1.71.0-beta.6/govard_1.71.0-beta.6_Linux_arm64.tar.gz"
      sha256 "5273e683067c6905653bf727ad54e9b852644a34869ffececb5dd31b1fd9c1e0"
      define_method(:install) do
        bin.install "govard"
      end
    end
  end

  def post_install
    (bin/".install-source").write "brew"
  end

  test do
    system "#{bin}/govard", "version"
  end
end
